version: '3'

services:
  app:
    container_name: cicd-basic
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 9999:9999
    environment:
      - PORT=9999
